# Generated by Django 5.0.1 on 2025-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory'), ('consumable', 'Consumable'), ('key', 'Key Item'), ('material', 'Material')], max_length=20)),
                ('icon_name', models.CharField(max_length=100)),
                ('buy_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('is_stackable', models.BooleanField(default=True)),
                ('max_stack', models.IntegerField(default=99)),
                ('is_usable_in_battle', models.BooleanField(default=False)),
                ('is_usable_in_field', models.BooleanField(default=False)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('mp_bonus', models.IntegerField(default=0)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('magic_attack_bonus', models.IntegerField(default=0)),
                ('magic_defense_bonus', models.IntegerField(default=0)),
                ('speed_bonus', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PythonConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('syntax_example', models.TextField()),
                ('documentation_link', models.URLField(blank=True)),
            ],
        ),
    ]
