# Generated by Django 5.0.1 on 2025-09-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='required_lesson',
            field=models.ForeignKey(blank=True, help_text='Lesson that must be completed to use this item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson'),
        ),
    ]
