# Generated by Django 5.0.1 on 2025-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField(default=0)),
                ('times_used', models.IntegerField(default=0)),
                ('first_learned', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'concept_mastery',
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_mp', models.IntegerField(default=50)),
                ('current_mp', models.IntegerField(default=50)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('magic_attack', models.IntegerField(default=8)),
                ('magic_defense', models.IntegerField(default=4)),
                ('speed', models.IntegerField(default=10)),
                ('sprite_name', models.CharField(blank=True, max_length=100)),
                ('portrait_name', models.CharField(blank=True, max_length=100)),
                ('experience_reward', models.IntegerField(default=10)),
                ('gold_reward', models.IntegerField(default=5)),
                ('ai_type', models.CharField(default='aggressive', max_length=50)),
                ('skill_weights', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'enemies',
                'db_table': 'enemies',
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_mp', models.IntegerField(default=50)),
                ('current_mp', models.IntegerField(default=50)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('magic_attack', models.IntegerField(default=8)),
                ('magic_defense', models.IntegerField(default=4)),
                ('speed', models.IntegerField(default=10)),
                ('sprite_name', models.CharField(blank=True, max_length=100)),
                ('portrait_name', models.CharField(blank=True, max_length=100)),
                ('personality', models.TextField(blank=True)),
                ('backstory', models.TextField(blank=True)),
                ('affinity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'party_members',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_mp', models.IntegerField(default=50)),
                ('current_mp', models.IntegerField(default=50)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=5)),
                ('magic_attack', models.IntegerField(default=8)),
                ('magic_defense', models.IntegerField(default=4)),
                ('speed', models.IntegerField(default=10)),
                ('sprite_name', models.CharField(blank=True, max_length=100)),
                ('portrait_name', models.CharField(blank=True, max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('skill_points', models.IntegerField(default=0)),
                ('story_flags', models.JSONField(blank=True, default=dict)),
                ('gold', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('equipment_slot', models.CharField(blank=True, choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], max_length=20)),
            ],
            options={
                'db_table': 'player_inventory',
            },
        ),
    ]
