# Generated by Django 5.0.1 on 2025-09-25 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0002_initial'),
        ('characters', '0001_initial'),
        ('core', '0001_initial'),
        ('world', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptmastery',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pythonconcept'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='guaranteed_drops',
            field=models.ManyToManyField(blank=True, related_name='guaranteed_by_enemies', to='core.gameitem'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='resistant_to',
            field=models.ManyToManyField(blank=True, related_name='enemies_resistant_to', to='battles.elementtype'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='teaches_concept',
            field=models.ForeignKey(blank=True, help_text='Python concept players learn by defeating this enemy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pythonconcept'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='weak_to',
            field=models.ManyToManyField(blank=True, related_name='enemies_weak_to', to='battles.elementtype'),
        ),
        migrations.AddField(
            model_name='partymember',
            name='special_skills',
            field=models.ManyToManyField(blank=True, to='battles.skill'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_here', to='world.location'),
        ),
        migrations.AddField(
            model_name='player',
            name='learned_concepts',
            field=models.ManyToManyField(related_name='players_who_learned', through='characters.ConceptMastery', to='core.pythonconcept'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partymember',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='characters.player'),
        ),
        migrations.AddField(
            model_name='conceptmastery',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.player'),
        ),
        migrations.AddField(
            model_name='playerinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameitem'),
        ),
        migrations.AddField(
            model_name='playerinventory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='characters.player'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptmastery',
            unique_together={('player', 'concept')},
        ),
        migrations.AlterUniqueTogether(
            name='playerinventory',
            unique_together={('player', 'item')},
        ),
    ]
