# Generated by Django 5.0.1 on 2025-09-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0001_initial'),
        ('characters', '0001_initial'),
        ('core', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='concepts_used',
            field=models.ManyToManyField(blank=True, to='core.pythonconcept'),
        ),
        migrations.AddField(
            model_name='battle',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles', to='world.location'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.player'),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='battleturn',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='battles.battleparticipant'),
        ),
        migrations.AddField(
            model_name='battleturn',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='battleturn',
            name='targets',
            field=models.ManyToManyField(related_name='targeted_in_turns', to='battles.battleparticipant'),
        ),
        migrations.AddField(
            model_name='skill',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battles.elementtype'),
        ),
        migrations.AddField(
            model_name='skill',
            name='required_concept',
            field=models.ForeignKey(blank=True, help_text='Python concept needed to learn this skill', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pythonconcept'),
        ),
    ]
