# Generated by Django 5.0.1 on 2025-09-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='hints',
        ),
        migrations.AddField(
            model_name='challenge',
            name='expected_output',
            field=models.JSONField(blank=True, default=dict, help_text='Expected output for automatic validation'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hint',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='lessons.challenge'),
        ),
        migrations.AddField(
            model_name='hint',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='playerlessonprogress',
            name='completed_challenges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='playerlessonprogress',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
